import { ContentBlock } from "@sarathi/api-types";
import { BlockRenderer } from "@/components/blocks/BlockRenderer";

const FIXTURE_BLOCKS: ContentBlock[] = [
  { id: "h1", type: "heading", text: "Introduction to Calculus", level: 1 },
  { id: "h2", type: "heading", text: "Derivatives", level: 2 },
  { id: "t1", type: "text", content: "A derivative measures how a function changes as its input changes. Loosely speaking, a derivative can be thought of as how much one quantity is changing in response to changes in some other quantity." },
  { 
    id: "l1", 
    type: "list", 
    ordered: true, 
    items: [
      "Find the slope of the secant line.",
      "Take the limit as the distance between points approaches zero.",
      "This limit is the derivative!"
    ]
  },
  {
    id: "c1",
    type: "code",
    language: "python",
    code: "def derivative(f, x, h=1e-5):\n    return (f(x + h) - f(x)) / h"
  },
  {
    id: "m1",
    type: "math",
    display: true,
    expression: "f'(x) = \\lim_{h \\to 0} \\frac{f(x+h) - f(x)}{h}"
  },
  {
    id: "m2",
    type: "math",
    display: false,
    expression: "\\frac{d}{dx} x^n = nx^{n-1}"
  },
  {
    id: "co_info",
    type: "callout",
    variant: "info",
    title: "Did you know?",
    content: "Newton and Leibniz independently discovered calculus in the 17th century."
  },
  {
    id: "co_tip",
    type: "callout",
    variant: "tip",
    title: "Study Tip",
    content: "Always check your units when calculating related rates."
  },
  {
    id: "co_warning",
    type: "callout",
    variant: "warning",
    title: "Common Pitfall",
    content: "Don't forget the chain rule when differentiating composite functions."
  },
  {
    id: "co_misc",
    type: "callout",
    variant: "misconception",
    title: "Misconception",
    content: "A function being continuous does NOT mean it is differentiable."
  },
  {
    id: "co_ai",
    type: "callout",
    variant: "ai_notice",
    content: "This explanation was generated by AI and may contain inaccuracies."
  },
  {
    id: "ex1",
    type: "example",
    title: "Power Rule Example",
    content: "Find the derivative of f(x) = x³. Using the power rule with n=3, we get f'(x) = 3x²."
  },
  {
    id: "an1",
    type: "analogy",
    content: "Think of a function as a car's position on a road. The derivative is the car's speedometer reading at any exact moment."
  },
  {
    id: "s1",
    type: "step",
    content: "First, identify the inner function g(x) and the outer function f(u).",
    reveal: false
  },
  {
    id: "q1",
    type: "quiz_inline",
    question: "What is the derivative of e^x?",
    options: ["x * e^(x-1)", "e^x", "1 / e^x", "ln(x)"],
    correct_option_index: 1,
    feedback: "The exponential function base e is unique because it is its own derivative!"
  },
  {
    id: "ip1",
    type: "image_prompt",
    prompt: "A graph showing a curve with a tangent line touching at one point",
    alt_text: "Graph of a curve with tangent line"
  },
  { id: "d1", type: "divider" },
  // Unknown block to test fallback
  { id: "u1", type: "missing_type" as any, content: "This is some unknown block" } as any
];

export default function DebugBlocksPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto py-12 px-6">
        <div className="mb-8 pb-4 border-b border-border">
          <h1 className="text-3xl font-bold tracking-tight mb-2">Block Renderers Debug</h1>
          <p className="text-muted-foreground">
            Verifying the 12 frozen block types + unknown fallback
          </p>
        </div>
        
        <div className="space-y-2">
          {FIXTURE_BLOCKS.map((block, idx) => (
            <div key={`${block.id}-${idx}`} className="group relative">
              <div className="absolute -left-12 top-0 bottom-0 w-8 flex items-start justify-end pt-4 opacity-0 group-hover:opacity-100 transition-opacity">
                <span className="text-[10px] font-mono text-muted-foreground uppercase rotate-[-90deg] origin-bottom-right mt-8 mr-2 whitespace-nowrap">
                  {block.type}
                </span>
              </div>
              <BlockRenderer block={block} />
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
