/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Usage */
        get: operations["get_usage_health_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{lesson_id}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Checkpoint */
        post: operations["generate_checkpoint_api_v1_lessons__lesson_id__checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/checkpoints/{checkpoint_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Checkpoint */
        post: operations["submit_checkpoint_api_v1_checkpoints__checkpoint_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lesson Metadata
         * @description 17 GET /api/v1/lessons/{id} - metadata only
         */
        get: operations["get_lesson_metadata_api_v1_lessons__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Lesson
         * @description 18 POST /api/v1/lessons/{id}/start - marks in progress, returns thread id
         */
        post: operations["start_lesson_api_v1_lessons__id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Lesson Content
         * @description 19 GET /api/v1/lessons/{id}/content - SSE stream of ContentBlocks
         */
        get: operations["stream_lesson_content_api_v1_lessons__id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{id}/reexplain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reexplain Lesson Block
         * @description 19b POST /api/v1/lessons/{id}/reexplain - SSE stream
         */
        post: operations["reexplain_lesson_block_api_v1_lessons__id__reexplain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Lesson
         * @description 20 POST /api/v1/lessons/{id}/complete
         */
        post: operations["complete_lesson_api_v1_lessons__id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lessons/{id}/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Lesson Signal
         * @description 25 POST /api/v1/lessons/{id}/signals
         */
        post: operations["create_lesson_signal_api_v1_lessons__id__signals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tutor/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Tutor Message
         * @description 21 POST /api/v1/tutor/messages - SSE stream
         */
        post: operations["send_tutor_message_api_v1_tutor_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tutor/threads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tutor Thread
         * @description 22 GET /api/v1/tutor/threads/{id}
         */
        get: operations["get_tutor_thread_api_v1_tutor_threads__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Get the current learner's profile.
         *     Lazily creates a new profile record if this is the learner's first request.
         */
        get: operations["get_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Signals
         * @description 26 GET /api/v1/users/me/signals
         */
        get: operations["get_my_signals_api_v1_users_me_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get My Progress
         * @description 27 GET /api/v1/users/me/progress
         */
        get: operations["get_my_progress_api_v1_users_me_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostic/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Diagnostic Session */
        post: operations["start_diagnostic_session_api_v1_diagnostic_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostic/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resume Diagnostic Session */
        get: operations["resume_diagnostic_session_api_v1_diagnostic_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostic/sessions/{session_id}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer Diagnostic Question */
        post: operations["answer_diagnostic_question_api_v1_diagnostic_sessions__session_id__answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostic/sessions/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Diagnostic Session */
        post: operations["complete_diagnostic_session_api_v1_diagnostic_sessions__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile/learner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profile_learner_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Profile */
        patch: operations["patch_profile_api_v1_profile_learner_patch"];
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_v1_goals_get"];
        put?: never;
        /** Create Goal */
        post: operations["create_goal_api_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Goal */
        patch: operations["update_goal_api_v1_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Plan Endpoint */
        post: operations["generate_plan_endpoint_api_v1_goals__goal_id__plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_v1_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plans/{plan_id}/replan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replan */
        post: operations["replan_api_v1_plans__plan_id__replan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adaptations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Adaptations */
        get: operations["get_adaptations_api_v1_adaptations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/adaptations/{id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond Adaptation */
        post: operations["respond_adaptation_api_v1_adaptations__id__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Dev Token */
        post: operations["generate_dev_token_dev_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Accessibility */
        Accessibility: {
            /**
             * Font Scale
             * @default 1
             */
            font_scale: number;
            /**
             * Reduced Motion
             * @default false
             */
            reduced_motion: boolean;
            /**
             * Screen Reader
             * @default false
             */
            screen_reader: boolean;
            /**
             * Dyslexia Font
             * @default false
             */
            dyslexia_font: boolean;
        };
        /**
         * AdaptationAction
         * @enum {string}
         */
        AdaptationAction: "insert_prerequisite" | "slow_pace" | "reexplain_concept" | "compress_forward" | "reorder" | "extend_timeline" | "no_op";
        /** AdaptationEventResponse */
        AdaptationEventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            trigger: components["schemas"]["AdaptationTrigger"];
            action: components["schemas"]["AdaptationAction"];
            /** Reason */
            reason: string;
            /** Timeline Impact */
            timeline_impact: string;
            /** Before */
            before: {
                [key: string]: unknown;
            };
            /** After */
            after: {
                [key: string]: unknown;
            };
            /** Accepted */
            accepted: boolean | null;
        };
        /** AdaptationListResponse */
        AdaptationListResponse: {
            /** Items */
            items: components["schemas"]["AdaptationEventResponse"][];
            /** Total */
            total: number;
        };
        /** AdaptationRespondRequest */
        AdaptationRespondRequest: {
            /** Accepted */
            accepted: boolean;
        };
        /**
         * AdaptationTrigger
         * @enum {string}
         */
        AdaptationTrigger: "struggling" | "stuck" | "racing" | "stalled" | "decaying";
        /** CheckpointAttemptResponse */
        CheckpointAttemptResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Score */
            score: number;
            /** Mastery Deltas */
            mastery_deltas: components["schemas"]["MasteryDelta"][];
            /** Feedback */
            feedback: components["schemas"]["ItemFeedback"][];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** CheckpointItem */
        CheckpointItem: {
            /** Id */
            id: string;
            /** Type */
            type: string;
            /** Question */
            question: string;
            /** Options */
            options?: string[] | null;
            /** Concept Ids */
            concept_ids: string[];
        };
        /** CheckpointResponse */
        CheckpointResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Lesson Id
             * Format: uuid
             */
            lesson_id: string;
            /** Items */
            items: components["schemas"]["CheckpointItem"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CheckpointSubmitRequest */
        CheckpointSubmitRequest: {
            /** Responses */
            responses: {
                [key: string]: unknown;
            };
        };
        /**
         * DepthPref
         * @enum {string}
         */
        DepthPref: "breadth_survey" | "depth_mastery";
        /** DevAuthRequest */
        DevAuthRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** DiagnosticActionResponse */
        DiagnosticActionResponse: {
            /**
             * Id
             * Format: uuid
             * @description The session ID
             */
            id: string;
            /** @description The status of the diagnostic session */
            status: components["schemas"]["DiagnosticStatus"];
            /**
             * Complete
             * @description True if the diagnostic is complete and ready to be finalized
             */
            complete: boolean;
            /** @description The next question to ask the user */
            question?: components["schemas"]["NextQuestionSchema"] | null;
            /** @description Progress indicator */
            progress?: components["schemas"]["DiagnosticProgress"] | null;
        };
        /** DiagnosticAnswerRequest */
        DiagnosticAnswerRequest: {
            /** Answer */
            answer: string;
        };
        /** DiagnosticProgress */
        DiagnosticProgress: {
            /** Answered */
            answered: number;
            /**
             * Estimated Total
             * @default 10
             */
            estimated_total: number;
        };
        /**
         * DiagnosticStatus
         * @enum {string}
         */
        DiagnosticStatus: "started" | "completed" | "abandoned";
        /** GoalCreate */
        GoalCreate: {
            /**
             * Raw Input
             * @description The raw natural language input describing the goal.
             */
            raw_input: string;
        };
        /** GoalResponse */
        GoalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Raw Input */
            raw_input: string;
            /** Normalized Topic */
            normalized_topic: string;
            /** Target Level */
            target_level: string;
            /** Deadline */
            deadline: string | null;
            /** Motivation Hint */
            motivation_hint: string | null;
            /** Is Educational */
            is_educational: boolean;
            /** Clarification Needed */
            clarification_needed: string | null;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GoalUpdate */
        GoalUpdate: {
            /**
             * Normalized Topic
             * @description Corrected topic.
             */
            normalized_topic?: string | null;
            /**
             * Target Level
             * @description Corrected target level.
             */
            target_level?: ("beginner" | "intermediate" | "advanced") | null;
            /**
             * Deadline
             * @description Corrected deadline.
             */
            deadline?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemFeedback */
        ItemFeedback: {
            /** Item Id */
            item_id: string;
            /** Correct */
            correct: boolean;
            /** Explanation */
            explanation: string;
        };
        /** JobError */
        JobError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /**
         * JobKind
         * @enum {string}
         */
        JobKind: "plan_generation" | "replan";
        /** JobResponse */
        JobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            /** Progress */
            progress: number;
            /** Progress Message */
            progress_message?: string | null;
            /** Result */
            result?: components["schemas"]["PlanGenerationResult"] | components["schemas"]["ReplanResult"] | null;
            error?: components["schemas"]["JobError"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** LearnerProfilePatchRequest */
        LearnerProfilePatchRequest: {
            /** Prior Knowledge */
            prior_knowledge?: {
                [key: string]: unknown;
            } | null;
            pace?: components["schemas"]["Pace"] | null;
            representation_pref?: components["schemas"]["RepresentationPref"] | null;
            scaffolding_pref?: components["schemas"]["ScaffoldingPref"] | null;
            depth_pref?: components["schemas"]["DepthPref"] | null;
            motivation?: components["schemas"]["Motivation"] | null;
            /** Session Minutes */
            session_minutes?: number | null;
            /** Language */
            language?: string | null;
            accessibility?: components["schemas"]["Accessibility"] | null;
        };
        /** LearnerProfileResponse */
        LearnerProfileResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Profile Version */
            profile_version: number;
            /** Prior Knowledge */
            prior_knowledge: {
                [key: string]: unknown;
            };
            pace: components["schemas"]["Pace"];
            representation_pref: components["schemas"]["RepresentationPref"];
            scaffolding_pref: components["schemas"]["ScaffoldingPref"];
            depth_pref: components["schemas"]["DepthPref"];
            motivation: components["schemas"]["Motivation"];
            /** Session Minutes */
            session_minutes: number;
            /** Language */
            language: string;
            accessibility: components["schemas"]["Accessibility"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** LessonResponse */
        LessonResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Module Id
             * Format: uuid
             */
            module_id: string;
            /** Order Index */
            order_index: number;
            /** Title */
            title: string;
            /** Objective */
            objective: string;
            /** Concept Ids */
            concept_ids: string[];
            /** Est Minutes */
            est_minutes: number;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MasteryDelta */
        MasteryDelta: {
            /**
             * Concept Id
             * Format: uuid
             */
            concept_id: string;
            /** Delta */
            delta: number;
        };
        /** MasteryStateResponse */
        MasteryStateResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Concept Id
             * Format: uuid
             */
            concept_id: string;
            /** Score */
            score: string;
            /** Confidence */
            confidence: string;
            /** Attempts */
            attempts: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string | null;
            /** Locale */
            locale: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Has Learner Profile
             * @default false
             */
            has_learner_profile: boolean;
            /** Profile Version */
            profile_version?: number | null;
        };
        /** ModuleResponse */
        ModuleResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /** Order Index */
            order_index: number;
            /** Title */
            title: string;
            /** Objective */
            objective: string;
            /** Rationale */
            rationale: string;
            /** Est Minutes */
            est_minutes: number;
            /** Status */
            status: string;
            /** Lessons */
            lessons: components["schemas"]["LessonResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * Motivation
         * @enum {string}
         */
        Motivation: "exam" | "career" | "curiosity" | "project";
        /** NextQuestionSchema */
        NextQuestionSchema: {
            /** Question Text */
            question_text: string;
            /** Question Type */
            question_type: string;
            /** Options */
            options?: string[] | null;
        };
        /**
         * Pace
         * @enum {string}
         */
        Pace: "deliberate" | "standard" | "fast";
        /** PaginatedResponse[GoalResponse] */
        PaginatedResponse_GoalResponse_: {
            /** Data */
            data: components["schemas"]["GoalResponse"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Has More */
            has_more: boolean;
        };
        /** PlanGenerationResult */
        PlanGenerationResult: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
        };
        /** PlanResponse */
        PlanResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Goal Id
             * Format: uuid
             */
            goal_id: string;
            /** Version */
            version: number;
            /** Title */
            title: string;
            /** Rationale */
            rationale: string;
            /** Profile Version */
            profile_version: number;
            /** Status */
            status: string;
            /** Modules */
            modules: components["schemas"]["ModuleResponse"][];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReexplainRequest */
        ReexplainRequest: {
            /**
             * Block Id
             * Format: uuid
             */
            block_id: string;
            /** Reason */
            reason?: string | null;
        };
        /** ReplanResult */
        ReplanResult: {
            /**
             * Plan Id
             * Format: uuid
             */
            plan_id: string;
            /**
             * Adaptation Event Id
             * Format: uuid
             */
            adaptation_event_id: string;
        };
        /**
         * RepresentationPref
         * @enum {string}
         */
        RepresentationPref: "concrete_first" | "abstract_first";
        /**
         * ScaffoldingPref
         * @enum {string}
         */
        ScaffoldingPref: "worked_examples" | "guided_discovery";
        /** SignalCreate */
        SignalCreate: {
            /** Block Id */
            block_id?: string | null;
            type: components["schemas"]["SignalType"];
            /**
             * Value
             * @default {}
             */
            value: {
                [key: string]: unknown;
            };
        };
        /** SignalResponse */
        SignalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Lesson Id */
            lesson_id: string | null;
            /** Block Id */
            block_id: string | null;
            type: components["schemas"]["SignalType"];
            /** Value */
            value: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * SignalType
         * @enum {string}
         */
        SignalType: "checkpoint_score" | "confusion_flag" | "time_on_block" | "hint_requested" | "retry" | "inline_check_failed" | "skip" | "session_abandon" | "revisit";
        /** TutorMessageRequest */
        TutorMessageRequest: {
            /**
             * Lesson Id
             * Format: uuid
             */
            lesson_id: string;
            /** Thread Id */
            thread_id?: string | null;
            /** Content */
            content: string;
            /** Context Block Id */
            context_block_id?: string | null;
        };
        /** UsageResponse */
        UsageResponse: {
            /** Agents */
            agents: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Total Cost Inr */
            total_cost_inr: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_usage_health_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
        };
    };
    generate_checkpoint_api_v1_lessons__lesson_id__checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_checkpoint_api_v1_checkpoints__checkpoint_id__submit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                checkpoint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckpointSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointAttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_metadata_api_v1_lessons__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_lesson_api_v1_lessons__id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_lesson_content_api_v1_lessons__id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reexplain_lesson_block_api_v1_lessons__id__reexplain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReexplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_lesson_api_v1_lessons__id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lesson_signal_api_v1_lessons__id__signals_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_tutor_message_api_v1_tutor_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TutorMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tutor_thread_api_v1_tutor_threads__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    get_my_signals_api_v1_users_me_signals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalResponse"][];
                };
            };
        };
    };
    get_my_progress_api_v1_users_me_progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasteryStateResponse"][];
                };
            };
        };
    };
    start_diagnostic_session_api_v1_diagnostic_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticActionResponse"];
                };
            };
        };
    };
    resume_diagnostic_session_api_v1_diagnostic_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    answer_diagnostic_question_api_v1_diagnostic_sessions__session_id__answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticActionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_diagnostic_session_api_v1_diagnostic_sessions__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_profile_api_v1_profile_learner_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerProfileResponse"];
                };
            };
        };
    };
    patch_profile_api_v1_profile_learner_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerProfileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_goals_api_v1_goals_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sort_by?: string | null;
                sort_desc?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_GoalResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_goal_api_v1_goals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_goal_api_v1_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_plan_endpoint_api_v1_goals__goal_id__plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replan_api_v1_plans__plan_id__replan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_adaptations_api_v1_adaptations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdaptationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_adaptation_api_v1_adaptations__id__respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdaptationRespondRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_dev_token_dev_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
