"""adaptation_events

Revision ID: be50339179e3
Revises: 1708e9f5dfd6
Create Date: 2026-08-30 09:01:17.495023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be50339179e3'
down_revision: Union[str, Sequence[str], None] = '1708e9f5dfd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptation_events',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('trigger', postgresql.ENUM('struggling', 'stuck', 'racing', 'stalled', 'decaying', name='adaptation_trigger'), nullable=False),
    sa.Column('action', postgresql.ENUM('insert_prerequisite', 'slow_pace', 'reexplain_concept', 'compress_forward', 'reorder', 'extend_timeline', 'no_op', name='adaptation_action'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('timeline_impact', sa.Text(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.CheckConstraint('length(reason) > 0', name='adaptation_events_reason_check'),
    sa.CheckConstraint('length(timeline_impact) > 0', name='adaptation_events_timeline_impact_check'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_adaptation_events_user_id_created_at', 'adaptation_events', ['user_id', 'created_at'], unique=False, postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_adaptation_events_user_id_created_at', table_name='adaptation_events', postgresql_using='btree', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('adaptation_events')
    # ### end Alembic commands ###
