"""add_learner_profiles_and_concepts

Revision ID: cbe458a6eb04
Revises: 552cb80eaf71
Create Date: 2026-08-29 15:24:48.159729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbe458a6eb04'
down_revision: Union[str, Sequence[str], None] = '552cb80eaf71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('prerequisite_ids', postgresql.ARRAY(sa.Uuid()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnostic_sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('started', 'completed', 'abandoned', name='diagnostic_status_enum'), nullable=False),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('derived_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnostic_sessions_user_id'), 'diagnostic_sessions', ['user_id'], unique=False)
    op.create_table('learner_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('prior_knowledge', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pace', postgresql.ENUM('deliberate', 'standard', 'fast', name='pace_enum'), nullable=False),
    sa.Column('representation_pref', postgresql.ENUM('concrete_first', 'abstract_first', name='representation_pref_enum'), nullable=False),
    sa.Column('scaffolding_pref', postgresql.ENUM('worked_examples', 'guided_discovery', name='scaffolding_pref_enum'), nullable=False),
    sa.Column('depth_pref', postgresql.ENUM('breadth_survey', 'depth_mastery', name='depth_pref_enum'), nullable=False),
    sa.Column('motivation', postgresql.ENUM('exam', 'career', 'curiosity', 'project', name='motivation_enum'), nullable=False),
    sa.Column('session_minutes', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('accessibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_version', name='uq_learner_profile_user_version')
    )
    op.create_index(op.f('ix_learner_profiles_user_id'), 'learner_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_profiles_user_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_index(op.f('ix_diagnostic_sessions_user_id'), table_name='diagnostic_sessions')
    op.drop_table('diagnostic_sessions')
    op.drop_table('concepts')
    # ### end Alembic commands ###
