"""goal additional fields

Revision ID: f2c2328faf13
Revises: af22b8f8c1b7
Create Date: 2026-08-29 21:10:50.601018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c2328faf13'
down_revision: Union[str, Sequence[str], None] = 'af22b8f8c1b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('motivation_hint', sa.String(), nullable=True))
    op.add_column('goals', sa.Column('is_educational', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('goals', sa.Column('clarification_needed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'clarification_needed')
    op.drop_column('goals', 'is_educational')
    op.drop_column('goals', 'motivation_hint')
    # ### end Alembic commands ###
